### ISSUE TITLE
Enable configuration of htmlhint through VS Code. 

### ISSUE THREAD

**Issue by mike-kaufman** [Microsoft/vscode-htmlhint#1]

**Comment by mike-kaufman** [comment]
Should be fixed with [change 3e5979d](https://github.com/Microsoft/vscode-htmlhint/commit/3e5979d78cafd18d4a2e3dfb7801f40c630aa2ad).  Extension should now look for and find .htmlhintrc files in the same manner as the command-line tool.

**Comment by vinayakvinay** [comment]
Extension doesn't consider custom .htmlhintrc file with latest VSCode v1.18.1.
I installed htmlhint locally as well as globally with npm.
