### ISSUE TITLE
Lint errors persist

### ISSUE THREAD

**Issue by tympapost** [Microsoft/vscode-htmlhint#23]
I dunno if I'm doing something wrong, but opening and closing html files with lint errors doesn't clear up the lint errors from the "Problems" tab.
Other linters show only the errors from currently open files in editors. This one just adds errors and you have to restart VSCode to get rid of them.
Can we get an option to tweak this behavior?

**Comment by peterdanis** [comment]
I have the same issue.

VS Code 1.13.0
HTML 0.3.3

![image](https://user-images.githubusercontent.com/26599181/27121559-249a543e-50e8-11e7-9316-9fcfe2a0f586.png)

**Comment by peterdanis** [comment]
You can close this issue. Closed files will not stay in "Problems" tab anymore. Tested on:
VS Code 1.14.2
HTML 0.3.3

**Comment by gian1200** [comment]
I'm facing exactly this issue. Should I create a new issue or open this one again?
VS Code 1.34.0
HTMLHint: 0.6.0
