### ISSUE TITLE
Add file extensions support

### ISSUE THREAD

**Issue by fsmaia** [Microsoft/vscode-htmlhint#3]
It would be nice to have file extensions support, in order to run HTLMHint also in template files (like Freemarker, Velocity, etc).

**Comment by alexbet** [comment]
I second this. It would be great if can set which file extensions HTMLHint should lint. For example, I need PHP file support.

**Comment by KatieMFritz** [comment]
Solved in #29 - please try with your own extensions and report back, once the new option is available!

**Comment by mike-kaufman** [comment]
This has been addressed & an update has now been published to the VS Code extension gallery.
