### ISSUE TITLE
Support for config file e.g. htmlhint.json

### ISSUE THREAD

**Issue by mnp-mid** [microsoft/vscode-htmlhint#37]
is there a way to tell Visual studio code to use htmlhint.json instead of redefining the content of the htmlhint.json in VSC again?

**Comment by mnp-mid** [comment]
We use htmlhint together with yarn and webpack like this:

htmlhint --config htmlhint.json "app/scripts/{,**}/*.html" "test/{,**}/*.html"

and so I have to redefine the rules in VSCode again.

**Comment by mike-kaufman** [comment]
@mnp-mid - see this PR: https://github.com/Microsoft/vscode-htmlhint/pull/35.  Happy to take contributions here.
