### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode-htmlhint#67]
Is the project still being maintained?
Please let us know, it's important for people that use this extension

**Comment by mike-kaufman** [comment]
Happy to review PRs.  Feel free to submit something if you'd like to see something changed.

**Comment by kanlukasz** [comment]
Sorry for no PR, i'm just PHP dev. It's easy to create tickets than to do PR. I know that but I asked because you have many bugs/tickets that have not been repaired for a long time.

**Comment by coliff** [comment]
@kanlukasz The htmlhint project went quiet for a while but it's actively being worked on now with a new release a few days ago and more updates planned.
https://github.com/htmlhint/HTMLHint/blob/develop/CHANGELOG.md

**Comment by kanlukasz** [comment]
@coliff my question was about the vscode addon, but thank you also for this information 😉

**Comment by coliff** [comment]
I think some of the bugs/limitations of the plugin reported here was down to HTMLHint though... if HTMLHint is updated hopefully this extension can too. :-)
