### ISSUE TITLE
Don't bundle htmlhint with this extension, use local version installed in project

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-htmlhint#8]
All the other linter extensions like eslint, tslint etc. do not bundle the linter with the extension, because projects can depend on specific versions of a linter (config file schemas can change, etc). If you bundle the linter, it is also impossible to update the linter if you have not released an update for the extension yet.

Please look for htmlhint in the node_modules folder in the currently opened project (relative to where .htmlhintrc is located) and if it can't be found, use a globally installed version, and if it still can't be found, print an error message.

**Comment by mike-kaufman** [comment]
@egamma, @dbaeumer - Any precedent around this?  I know that tslint/eslint is picking up the linter from local project's node_modules directory.  I explicitly didn't do that as I didn't want the user to have install a module to get the benefit of the linter.  Also wasn't always sure that, for html, there would be a project structure and/or a node-Modules folder.  

Anyway, if there's precedent in other linters let me know.

**Comment by felixfbecker** [comment]
The current problem is the best example: There has just recently been a fix in HTMLHint that enables it to work with Angular 2 templates. This extension is now stuck at the old version :/

**Comment by dbaeumer** [comment]
@mike-kaufman the rule should alwys be to prefer local installed libraries over bundled libraries. So in your case if you bundle htmlhint the loading sequence should be:

- use htmlhint from the workspace folder
- use global installed htmlhint
- use bundled htmlhint

**Comment by spicemix** [comment]
(Would be nice if this project came back to life at some point...)

**Comment by stevedenman** [comment]
Just to get things moving again, I've made a quick pull request https://github.com/Microsoft/vscode-htmlhint/pull/15 to use latest htmlhint - not ideal but angular2 files are now looking good @felixfbecker

**Comment by mike-kaufman** [comment]
The right fix here is illustrated in the tslint extension for vs code:  https://github.com/Microsoft/vscode-tslint/blob/master/tslint-server/src/server.ts#L268-L297.

**Comment by stevedenman** [comment]
@mike-kaufman yeah, that looks good. Would you like me to put together another PR with that?

**Comment by felixfbecker** [comment]
I would appreciate it, but I would replace the `existsSync` with its async counterpart 😉

**Comment by mike-kaufman** [comment]
@stevedenman  - if you want to code up a fix, that'd be great.  It should be fairly straightforward.  The only thing I'm not sure about is if we can rely on the embedded version of htmlhint if there isn't one in the user's project.  If we can't do this, then we'll impact existing users when they're upgraded, as they'll have to `npm install htmlhint`.

**Comment by mike-kaufman** [comment]
> I would replace the existsSync with its async counterpart 

You could do this, but I'm not clear on the benefit.  I *think* this code only runs when the extension is initialized, and I *think* this part of the extension runs in an isolated process, so the impact of doing the file read synchronously should be minimal.   I'm not 100% certain though, so LMK if I'm missing something.

Thanks!

**Comment by felixfbecker** [comment]
What is the disadavantage? The method is async and returns a promise anyway

**Comment by mike-kaufman** [comment]
> What is the disadavantage? The method is async and returns a promise anyway

In the cited tslint example above, only disadvantage is you'd have to restructure the (working) example, but that's minor.  Other sync io in the htmlhint extension (where it's looking for config files), you'd have to account for the validation call chain running asynchronously - I'm not sure if that will "just work".   

As I said in #9, I'll happily take a PR if you feel strongly about the removing sync io.  If it isn't obvious already, I haven't had lots of time to put into this extension. ;)  I'm happy to answer questions & publish updates to the PR, but I'd love to encourage the community to take an active role here. :)

**Comment by mike-kaufman** [comment]
@stevedenman - FYI I've got a change on my machine that fixes the issue so we'll use either the project-specific htmlhint, the global one, or the embedded one. I should have an updated module published in the next day.

**Comment by mike-kaufman** [comment]
OK, this should be fixed with the extension version 0.3.0 that is now on the gallery.  Please let me know if there are any issuses.
