### ISSUE TITLE
Does not work with 1.48.1 or 1.49.0 (insiders)

### ISSUE THREAD

**Issue by peku33** [microsoft/vscode-htmlhint#80]
The tool completely stopped working for 1.48.1 or 1.49.0.
Installed on two different PCs.
Created index.html document
Made some obvious mistake (single quotes instead of double)
No errors reported.

It is visible in settings, but nothing interesting in "Output".

**Comment by thllbrg** [comment]
Same here, reverting to 1.48.2 works.

**Comment by Raju** [comment]
1.49.0 stable not working at all....

**Comment by NicoSaar11** [comment]
Not working... I hope they can solve the problem

**Comment by lachieh** [comment]
I'm currently getting this error whenever I have the extension loaded which kills the extension host:
```
~/.vscode/extensions/mkaufman.htmlhint-0.8.0/node_modules/vscode-jsonrpc/lib/messageReader.js:200
                    throw new Error('Header must provide a Content-Length property.');
                    ^
[Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData 
(~/.vscode/extensions/mkaufman.htmlhint-0.8.0/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
	at Socket.<anonymous>
(~/.vscode/extensions/mkaufman.htmlhint-0.8.0/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
	at Socket.emit (events.js:223:5)
	at Socket.EventEmitter.emit (domain.js:475:20)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)] {
    vslsStack: [
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {}
    ]
  }
```

**Comment by mike-kaufman** [comment]
thanks @lachieh for the stack.  I'll see if I can find some time to understand what's going on here.

**Comment by AriciaL** [comment]
I'm on a Mac, I'm not sure how to see the stack to give any help. I would also appreciate if you could fix this. Thank you.

**Comment by mityaua** [comment]
The same situation. More details here https://github.com/microsoft/vscode/issues/107158

**Comment by mike-kaufman** [comment]
This should be fixed in the extension gallery now w/ version 0.10.0. Thanks to @aeschli for the fix here. Please LMK if you see different behavior.

**Comment by HarryAdney** [comment]
I've got this on VSCode version 1.52.0-insider and HTMLHint version 1.5.9

```
vscode-htmlhing LS: we have a connection
(node:5852) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Version: 1.52.0-insider (user setup)
Commit: f11635ef1199ba5c43d9b83bb8b33036ea26d5b1
Date: 2020-11-18T08:48:19.969Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
