### ISSUE TITLE
Does not work with 1.49.3 stable

### ISSUE THREAD

**Issue by Raju** [microsoft/vscode-htmlhint#82]
It stopped working for 1.49.3
![image](https://user-images.githubusercontent.com/42042961/94995507-60259b80-05bc-11eb-867f-916bd66d0ec2.png)

1. Created index.html file
2. Made some mistakes (single quotes instead of double, no HTML5 doctype)
3. No errors reported inside VS Code but in CLI it shows error.

![image](https://user-images.githubusercontent.com/42042961/94995545-ada20880-05bc-11eb-8c76-5ab384962074.png)

Not working....

Working in CLI but no error shown inside VS Code 1.49.3

![image](https://user-images.githubusercontent.com/42042961/94995526-92cf9400-05bc-11eb-953d-926178f0f7f0.png)

Settings which I had added,

![image](https://user-images.githubusercontent.com/42042961/94995562-c90d1380-05bc-11eb-92a2-a372e9f17187.png)

**Comment by mike-kaufman** [comment]
@Raju - this should be fixed now w/ version 0.10.0.  Thanks to @aeschli  for the fix here.  Please LMK if you see different behavior.

**Comment by Raju** [comment]
Thanks for the fix, it's working now.

![image](https://user-images.githubusercontent.com/42042961/95011399-0bcafc00-064e-11eb-88a5-baddfb611e32.png)
